#!/bin/bash
set -eo pipefail

read -rp "Control plane IP address = " control_plane_ip

echo 'Generating configurations'
talosctl gen config nigel-talos-homelab "https://${control_plane_ip}:6443" --config-patch @cert-rotate-patch.yaml --config-patch-control-plane @metric-server-patch.yaml --output-dir .out

echo 'Creating control plane node'
talosctl apply-config --insecure --nodes ${control_plane_ip} --file .out/controlplane.yaml
