apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    role: backup
  name: postgres-backup
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-csi-backup
  volumeMode: Filesystem
  volumeName: postgresql-backup