apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tdarr-ingressroute-tcp
  namespace: plex-management
spec:
  entryPoints:
    - tdarr-server
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ${service_name}
          port: 8266