apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: nfs-csi-authentik
provisioner: nfs.csi.k8s.io
parameters:
  server: ${nas_ip}
  share: ${root_path}/authentik
reclaimPolicy: Retain
mountOptions:
  - hard
  - nfsvers=4.1


