apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-ingressroute-tcp
  namespace: postgresql-recovery
spec:
  entryPoints:
    - postgresql-recovery
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ${service_name}
          port: postgres