#!/bin/bash
set -eo pipefail

read -rp "Control plane IP address = " control_plane_ip

echo 'Generating configurations'
talosctl gen config nigel-talos-homelab "https://${control_plane_ip}:6443" --output-dir .out

echo 'Creating control plane node'
talosctl apply-config --insecure --nodes ${control_plane_ip} --file .out/controlplane.yaml
