#!/bin/bash
set -eo pipefail

read -rp "Control plane IP address = " control_plane_ip

echo 'Generating configurations'
talosctl gen config nigel-talos-homelab "https://${control_plane_ip}:6443" --output-dir .out

echo 'Please change your config before proceeding'
read -p "Have you changed it? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

echo 'Creating control plane node'
talosctl apply-config --insecure --nodes ${control_plane_ip} --file .out/controlplane.yaml
