#!/bin/bash
set -eo pipefail

read -rp "Worker node(s) IP address(es) = " worker_ips

echo 'Creating worker node(s)'
ifs=$IFS
IFS=,
for worker in ${worker_ips}; do
  echo "Creating worker node [${worker}]"
  talosctl apply-config --insecure --nodes ${worker} --file .out/worker.yaml
done
IFS=$ifs

# echo 'Starting bootstrapping process'
# export TALOSCONFIG='.out/talosconfig'
# talosctl config endpoint ${control_plane_ip}

# Is this needed?
# talosctl config node ${control_plane_ip}

# echo 'getting service status'
# talosctl service apid status
# echo 'Bootstrapping etc'
# talosctl bootstrap

# # Wait for the cluster to become healthy
# i=0
# while [ $i -le 30 ]; do
#   echo "Checking cluster health try nr. ${i}"
#   talosctl health --wait-timeout 30s
#   ((i++))
# done

# echo 'Retrieving kubeconfig'
# talosctl kubeconfig .

# echo 'Configuring kubectl for the created kubeconfig'
# cp kubeconfig ~/.kube/homelab
# export KUBECONFIG="~/.kube/homelab"
