#!/bin/bash
set -eo pipefail

read -rp "Control plane IP address = " control_plane_ip

export TALOSCONFIG=".out/talosconfig"
talosctl config endpoint $control_plane_ip
talosctl config node $control_plane_ip

echo "Starting bootstrap"
talosctl bootstrap

talosctl kubeconfig .out/