apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  # imageName: "ghcr.io/cloudnative-pg/postgresql:17"
  logLevel: debug
  superuserSecret:
    name: ${superuser_secret}

  bootstrap:
    recovery:
      source: clusterBackup
      recoveryTarget:
        # Time base target for the recovery (Just change the date, it will use the WAL archives)
        # targetTime: "2025-06-25T18:00:03+00:00"
        targetTLI: "latest"

  replica: 
    enabled: true
    source: clusterBackup

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        endpointURL: ${synology_c2_endpoint}
        destinationPath: "s3://${bucket_name}/" 
        serverName: postgresql-cluster-postgresql-main
        s3Credentials:
          accessKeyId:
            name: ${synology_c2_secret}
            key: access_key
          secretAccessKey:
            name: ${synology_c2_secret}
            key: secret_key
  storage:
    size: 10Gi
    storageClass: "nfs-csi-postgresql"