apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: picture-of-the-day
  namespace: picture-of-the-day
spec:
  entryPoints:                 
    - internet
  routes:                           
  - kind: Rule
    match: Host(`pictures.nigelvanhattum.nl`) 
    services:                       
    - kind: Service
      name: picture-of-the-day
      namespace: picture-of-the-day
      passHostHeader: true
      port: 8080                     
      responseForwarding:
        flushInterval: 1ms
      # scheme: https
      strategy: RoundRobin    

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: picture-of-the-day-local
  namespace: picture-of-the-day
spec:
  entryPoints:                 
    - websecure
  routes:                           
  - kind: Rule
    match: Host(`pictures.local.nigelvanhattum.nl`) 
    services:                       
    - kind: Service
      name: picture-of-the-day
      namespace: picture-of-the-day
      passHostHeader: true
      port: 8080                     
      responseForwarding:
        flushInterval: 1ms
      # scheme: https
      strategy: RoundRobin   