apiVersion: v1
kind: PersistentVolume
metadata:
  name: fp-downloader-media
  labels:
    type: configdata
spec:
  storageClassName: nfs-csi-plex
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: ${ip_address}
    path: ${plex_rootmount}/LTT