apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${pv_name}
  labels:
    type: media
spec:
  storageClassName: nfs-csi-applications
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: ${ip_address}
    path: ${k8s_rootmount}/applications/ollama