apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${pv_name}
  labels:
    type: media-data
spec:
  storageClassName: nfs-csi-applications
  capacity:
    storage: 2Ti
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: ${ip_address}
    path: ${p2p_root}/Complete